version: "3"
services:
  mosquitto:
    container_name: mosquitto_server
    restart: always
    hostname: mosquitto_server
    image: eclipse-mosquitto:2.0.11
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    expose:
      - 1883
    logging:
      options:
        max-size: "1m"
        max-file: "5"

  monitor:
    container_name: monitor
    build: monitor
    restart: always
    environment:
      PYTHONUNBUFFERED: 1      
    depends_on:
      - mosquitto
    logging:
      options:
        max-size: "1m"
        max-file: "5"

  
volumes:
  db-data:
  